apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: gateway
  namespace: logging
  annotations:
    kubernetes.io/ingress.class: "bastion"
spec:
  virtualhost:
    fqdn: loki.logging.stage0.cybozu-ne.co
  routes:
    - conditions:
        - prefix: /api/prom/push
      services:
        - name: distributor
          port: 3100
    - conditions:
        - prefix: /api/prom/tail
      enableWebsockets: true
      services:
        - name: querier
          port: 3100
    - conditions:
        - prefix: /api/prom
      services:
        - name: query-frontend
          port: 3100
    - conditions:
        - prefix: /loki/api/v1/push
      services:
        - name: distributor
          port: 3100
    - conditions:
        - prefix: /loki/api/v1/tail
      enableWebsockets: true
      services:
        - name: querier
          port: 3100
    - conditions:
        - prefix: /loki/api
      services:
        - name: query-frontend
          port: 3100
